tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/binary'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/science'
tap 'homebrew/services'
tap 'neovim/neovim'
cask 'xquartz'
brew 'libyaml'
brew 'openssl@1.1'
brew 'gdbm'
brew 'openssl'
brew 'readline'
brew 'sqlite'
brew 'python'
brew 'ansible'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'boost'
brew 'libpng'
brew 'freetype'
brew 'fontconfig'
brew 'gettext'
brew 'libffi'
brew 'pcre'
brew 'glib'
brew 'pixman'
brew 'cairo'
brew 'cmake'
brew 'colordiff'
brew 'coreutils'
brew 'curl'
brew 'direnv'
brew 'libgpg-error'
brew 'libassuan'
brew 'libgcrypt'
brew 'libksba'
brew 'pth'
brew 'dirmngr'
brew 'git'
brew 'docker'
brew 'docker-machine'
brew 'jpeg'
brew 'libtiff'
brew 'wxmac'
brew 'erlang'
brew 'elixir'
brew 'pcre2'
brew 'fish'
brew 'gmp'
brew 'isl'
brew 'mpfr'
brew 'libmpc'
brew 'gcc'
brew 'ghq'
brew 'gnupg'
brew 'pinentry'
brew 'gpg-agent'
brew 'libusb'
brew 'libusb-compat'
brew 'gnupg2'
brew 'go'
brew 'heroku'
brew 'lua'
brew 'highlight'
brew 'htop-osx'
brew 'hub'
brew 'icu4c'
brew 'jemalloc'
brew 'oniguruma'
brew 'jq'
brew 'libevent'
brew 'libtermkey'
brew 'libtool'
brew 'libuv'
brew 'libvterm'
brew 'libxml2'
brew 'lv'
brew 'mas'
brew 'protobuf'
brew 'mobile-shell'
brew 'msgpack'
brew 'nkf'
brew 'node'
brew 'packer'
brew 'peco'
brew 'perl'
brew 'pinentry-mac'
brew 'pkg-config'
brew 'pstree'
brew 'ruby-build'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'rbenv-gemset'
brew 'reattach-to-user-namespace'
brew 'renameutils'
brew 'ruby'
brew 'ssh-copy-id'
brew 'terraform'
brew 'the_platinum_searcher'
brew 'xz'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'unibilium'
brew 'vim'
brew 'wget'
brew 'homebrew/dupes/unzip'
brew 'homebrew/science/r'
brew 'neovim/neovim/neovim'
cask 'alfred'
cask 'amazon-drive'
cask 'amazon-music'
cask 'appzapper'
cask 'atom'
cask 'bartender'
cask 'bathyscaphe'
cask 'betterzipql'
cask 'choosy'
cask 'couleurs'
cask 'cyberduck'
cask 'dash'
cask 'delibar'
cask 'dropbox'
cask 'duet'
cask 'flash-player'
cask 'font-noto-sans-cjk-jp'
cask 'font-ricty-diminished'
cask 'font-roboto'
cask 'font-source-code-pro'
cask 'font-source-han-code-jp'
cask 'github-desktop'
cask 'google-japanese-ime'
cask 'handbrake'
cask 'hosts'
cask 'hotswitch'
cask 'hyperswitch'
cask 'imageoptim'
cask 'iterm2'
cask 'kitematic'
cask 'libreoffice'
cask 'mysimbl'
cask 'mysqlworkbench'
cask 'onyx'
cask 'p4merge'
cask 'path-finder'
cask 'pg-commander'
cask 'psequel'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'rstudio'
cask 'sequel-pro'
cask 'silverlight'
cask 'simple-comic'
cask 'skype'
cask 'synergy'
cask 'vagrant'
cask 'virtualbox'
cask 'vivaldi'
cask 'vlc'
mas '1Password', id: 443987910
mas 'Amphetamine', id: 937984704
mas 'BetterSnapTool', id: 417375580
mas 'CotEditor', id: 1024640650
mas 'Fantastical 2', id: 975937182
mas 'Gyazo', id: 490085255
mas 'Kaleidoscope', id: 587512244
mas 'Keynote', id: 409183694
mas 'Kindle', id: 405399194
mas 'LINE', id: 539883307
mas 'Microsoft Remote Desktop', id: 715768417
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Pixelmator', id: 407963104
mas 'Pocket', id: 568494494
mas 'Pushbullet', id: 948415170
mas 'Quiver', id: 866773894
mas 'Reeder', id: 880001334
mas 'Remote Desktop', id: 409907375
mas 'Slack', id: 803453959
mas 'Spark', id: 1176895641
mas 'StuffIt Expander 16', id: 919269455
mas 'WiFi Explorer', id: 494803304
mas 'Xcode', id: 497799835
